package com.askyoutube.app.data.transcript

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

class TranscriptParserTest {

    private fun trackJson(
        baseUrl: String = "https://www.youtube.com/api/timedtext?v=abc",
        languageCode: String = "en",
        name: String = "English",
        kind: String? = null,
    ): String = buildString {
        append("""{"baseUrl":"$baseUrl","languageCode":"$languageCode",""")
        append(""""name":{"simpleText":"$name"}""")
        if (kind != null) append(""","kind":"$kind"""")
        append("}")
    }

    private fun watchPage(tracks: String): String =
        """{"responseContext":{},"playerResponse":{"videoDetails":{"videoId":"abc"},"captions":{"playerCaptionsTracklistRenderer":{"captionTracks":[$tracks]}}}}"""

    // ---- track extraction ------------------------------------------------

    @Test
    fun `extracts a single manual english track`() {
        val html = watchPage(trackJson())
        val tracks = TranscriptParser.extractCaptionTracks(html)
        assertEquals(1, tracks.size)
        assertEquals("en", tracks[0].languageCode)
        assertFalse(tracks[0].autoGenerated)
    }

    @Test
    fun `marks an asr track as auto generated`() {
        val html = watchPage(trackJson(kind = "asr"))
        val tracks = TranscriptParser.extractCaptionTracks(html)
        assertTrue(tracks[0].autoGenerated)
    }

    @Test
    fun `extracts several tracks`() {
        val html = watchPage(
            trackJson(languageCode = "en", name = "English") + "," +
                trackJson(languageCode = "de", name = "German")
        )
        val tracks = TranscriptParser.extractCaptionTracks(html)
        assertEquals(2, tracks.size)
        assertEquals(listOf("en", "de"), tracks.map { it.languageCode })
    }

    @Test
    fun `a page with no caption tracks yields an empty list`() {
        assertTrue(TranscriptParser.extractCaptionTracks("""{"captions":{}}""").isEmpty())
        assertTrue(TranscriptParser.extractCaptionTracks("not html at all").isEmpty())
    }

    @Test
    fun `brackets inside track names do not truncate the array`() {
        // A non-greedy regex would stop at the first ']' inside the name and hand
        // back malformed JSON. The bracket matcher has to see past it.
        val html = watchPage(trackJson(name = "English [auto] (2024)"))
        val tracks = TranscriptParser.extractCaptionTracks(html)
        assertEquals(1, tracks.size)
        assertEquals("English [auto] (2024)", tracks[0].name)
    }

    @Test
    fun `an escaped quote inside a name does not end the scan early`() {
        val html = """{"captionTracks":[{"baseUrl":"https://x/y","languageCode":"en","name":{"simpleText":"say \"hi\""}}]}"""
        val tracks = TranscriptParser.extractCaptionTracks(html)
        assertEquals(1, tracks.size)
        assertEquals("""say "hi"""", tracks[0].name)
    }

    // ---- track selection -------------------------------------------------

    private fun t(lang: String, asr: Boolean) =
        CaptionTrack("https://x/$lang", lang, lang, autoGenerated = asr)

    @Test
    fun `prefers a manual english track over an auto generated one`() {
        val chosen = TranscriptParser.selectTrack(listOf(t("en", true), t("en", false)))
        assertFalse(chosen!!.autoGenerated)
    }

    @Test
    fun `falls back to the auto generated english track`() {
        // The source app never asked for asr tracks, so videos with only auto
        // captions had no transcript at all. Defect D10.
        val chosen = TranscriptParser.selectTrack(listOf(t("en", true)))
        assertTrue(chosen!!.autoGenerated)
    }

    @Test
    fun `falls back to a non-english manual track when no english exists`() {
        val chosen = TranscriptParser.selectTrack(listOf(t("de", true), t("de", false)))
        assertEquals("de", chosen!!.languageCode)
        assertFalse(chosen.autoGenerated)
    }

    @Test
    fun `handles regional english tags`() {
        val chosen = TranscriptParser.selectTrack(listOf(t("en-GB", false), t("en-US", false)))
        assertEquals("en-GB", chosen!!.languageCode)
    }

    @Test
    fun `no tracks means no choice`() {
        assertNull(TranscriptParser.selectTrack(emptyList()))
    }

    // ---- cue parsing -----------------------------------------------------

    @Test
    fun `parses cues with their start times`() {
        val payload = """
            {"events":[
              {"tStartMs":0,"segs":[{"utf8":"hello "},{"utf8":"world"}]},
              {"tStartMs":1500,"segs":[{"utf8":"second line"}]}
            ]}
        """.trimIndent()

        val cues = TranscriptParser.parseCues(payload)
        assertEquals(2, cues.size)
        assertEquals("hello world", cues[0].text)
        assertEquals(0L, cues[0].startMs)
        assertEquals("second line", cues[1].text)
        assertEquals(1500L, cues[1].startMs)
    }

    @Test
    fun `newlines inside a segment become spaces`() {
        val payload = """{"events":[{"tStartMs":0,"segs":[{"utf8":"one\ntwo"}]}]}"""
        val cues = TranscriptParser.parseCues(payload)
        assertEquals("one two", cues[0].text)
    }

    @Test
    fun `events with no text are skipped`() {
        val payload = """
            {"events":[
              {"tStartMs":0,"segs":[]},
              {"tStartMs":100,"segs":[{"utf8":"   "}]},
              {"tStartMs":200,"segs":[{"utf8":"real"}]}
            ]}
        """.trimIndent()
        val cues = TranscriptParser.parseCues(payload)
        assertEquals(1, cues.size)
        assertEquals("real", cues[0].text)
    }

    @Test
    fun `a blank payload yields no cues`() {
        assertTrue(TranscriptParser.parseCues("").isEmpty())
        assertTrue(TranscriptParser.parseCues("   ").isEmpty())
    }

    @Test
    fun `malformed json yields no cues rather than throwing`() {
        // The timedtext endpoint is known to answer 200 with a zero-length or
        // HTML body; a broken payload must not crash the parser.
        assertTrue(TranscriptParser.parseCues("<html>not json</html>").isEmpty())
    }

    @Test
    fun `a payload with no events key yields no cues`() {
        assertTrue(TranscriptParser.parseCues("""{"other":true}""").isEmpty())
    }
}
