package com.askyoutube.app.data.transcript

import com.askyoutube.app.domain.Cue
import org.json.JSONArray
import org.json.JSONObject

/** One caption track advertised by the video's player response. */
data class CaptionTrack(
    val baseUrl: String,
    val languageCode: String,
    val name: String,
    /** "asr" marks an auto-generated track. Absent for a human-made one. */
    val autoGenerated: Boolean,
)

/**
 * Pulls caption tracks out of a YouTube watch page, and turns a caption payload
 * into cues. Pure string/JSON work with no network, so it is unit-tested
 * directly.
 *
 * There is no official YouTube captions API. This reads the player response
 * embedded in the watch page, which is the same approach the Python
 * youtube-transcript-api library takes.
 */
object TranscriptParser {

    private const val MARKER = "\"captionTracks\":"

    /**
     * Extracts and parses the captionTracks array.
     *
     * The array is located by marker and then bracket-matched rather than
     * regex-matched, because each track object contains nested objects and a
     * non-greedy `\[.*?\]` would stop at an inner bracket and hand back
     * malformed JSON.
     */
    fun extractCaptionTracks(html: String): List<CaptionTrack> {
        val start = html.indexOf(MARKER)
        if (start < 0) return emptyList()
        val arrayStart = html.indexOf('[', start + MARKER.length)
        if (arrayStart < 0) return emptyList()
        val arrayEnd = matchBracket(html, arrayStart) ?: return emptyList()

        val json = html.substring(arrayStart, arrayEnd + 1)
        val out = ArrayList<CaptionTrack>()
        val arr = JSONArray(json)
        for (i in 0 until arr.length()) {
            val o = arr.optJSONObject(i) ?: continue
            val baseUrl = o.optString("baseUrl")
            if (baseUrl.isNullOrBlank()) continue
            out += CaptionTrack(
                baseUrl = baseUrl,
                languageCode = o.optString("languageCode"),
                name = o.optJSONObject("name")?.optString("simpleText").orEmpty(),
                autoGenerated = o.optString("kind") == "asr",
            )
        }
        return out
    }

    /**
     * Picks the track to read.
     *
     * A human English track wins. Failing that, the auto-generated English one
     * — the source app never asked for `asr` tracks (it passed no
     * add_video_dashes), so videos with only auto captions came back with no
     * transcript at all. That was defect D10.
     */
    fun selectTrack(tracks: List<CaptionTrack>): CaptionTrack? {
        if (tracks.isEmpty()) return null
        val english = tracks.filter { it.languageCode.startsWith("en", ignoreCase = true) }
        return english.firstOrNull { !it.autoGenerated }
            ?: english.firstOrNull { it.autoGenerated }
            ?: tracks.firstOrNull { !it.autoGenerated }
            ?: tracks.first()
    }

    /**
     * Parses a `fmt=json3` caption payload into cues.
     *
     * Newlines inside a segment are turned into spaces so a chunk boundary never
     * lands in the middle of a sentence.
     */
    fun parseCues(payload: String): List<Cue> {
        if (payload.isBlank()) return emptyList()
        // Android's org.json is a trimmed build: JSONArray has no optJSONArray,
        // so the object is unwrapped first and the array pulled off the object.
        val events = try {
            JSONObject(payload).optJSONArray("events")
        } catch (e: Exception) {
            null
        } ?: return emptyList()

        val out = ArrayList<Cue>()
        for (i in 0 until events.length()) {
            val event = events.optJSONObject(i) ?: continue
            val segs = event.optJSONArray("segs") ?: continue
            val startMs = event.optLong("tStartMs", 0L)
            val sb = StringBuilder()
            for (j in 0 until segs.length()) {
                val seg = segs.optJSONObject(j) ?: continue
                val raw = seg.optString("utf8")
                if (raw.isEmpty()) continue
                sb.append(raw.replace("\n", " "))
            }
            val text = sb.toString().trim()
            if (text.isNotEmpty()) out += Cue(startMs, text)
        }
        return out
    }

    /** Index of the bracket matching the one at [open], or null if unbalanced. */
    private fun matchBracket(s: String, open: Int): Int? {
        var depth = 0
        var inString = false
        var escaped = false
        for (i in open until s.length) {
            val c = s[i]
            when {
                escaped -> escaped = false
                c == '\\' && inString -> escaped = true
                c == '"' -> inString = !inString
                inString -> Unit
                c == '[' -> depth++
                c == ']' -> {
                    depth--
                    if (depth == 0) return i
                }
            }
        }
        return null
    }
}
